function handles = DatabaseGUI (obj)
%DATABASEGUI This function initializes a Graphical-User-Interface to search
%for Gender, SentenceID, Person, Words, Phonems.

    % Creates the UI as it is being constructed by different handles.
    hFigure = figure('Visible','on',...
                     'Tag','TIMIT_MIT_DatabaseGUI',... 
                     'MenuBar','none',...
                     'Resize','off',...
                     'NumberTitle','off',...
                     'Name','Search Audio Data',...
                     'Position',[400 400 786 512]);
	
    % Centering the hFigure UI
    movegui(hFigure,'center');
    
    % Constructs the components of the UI 
    hDirectory = uicontrol('Style','edit',...
						'Position',[50 450 250 30],...
        				'String','Edit Direction',...
                        'FontName','Trebuchet',...
                        'FontSize',13,...
						'Callback',@searchDatabase);
                    
    hDirInfo = uicontrol('Style','text',...
                         'Position',[350 445 350 30],...
                         'String','',...
                         'FontName','Trebuchet',...
                         'Visible','on',...
                         'FontSize',13);
                     
                  uicontrol('Style','text',...
                            'Position',[45 405 95 30],...
                            'String','Gender',...
                            'FontName','Trebuchet',...
                            'FontSize',13);

    hGender = uicontrol('Style','popupmenu',...
						'Position',[45 385 95 30],...
                        'FontName','Trebuchet',...
                        'FontSize',13,...
						'String',{'','Male','Female'},...
                        'Callback',@Gender_value);
                    
                  uicontrol('Style','text',...
                            'Position',[150 405 85 30],...
                            'String','Person',...
                            'FontName','Trebuchet',...
                            'FontSize',13);

	hPerson = uicontrol('Style','popupmenu',...
						'Position',[150 385 85 30],...
                        'FontName','Trebuchet',...
                        'FontSize',13,...
						'String',{'','cpm0','vmh0','arc0','aem0','adc0','alk0',...
                                    'aeb0','alr0','bgt0','tlg0','bma1','apb0',...
                                    'add0','blv0','bcg0','bcg1'},...
                        'Callback',@Person_value);
                                
                     uicontrol('Style','text',...
                               'Position',[250 410 90 30],...
                               'String','SentenceID',...
                               'FontName','Trebuchet',...
                               'FontSize',13);

	hSentence = uicontrol('Style','edit',...
                          'FontName','Trebuchet',...
                          'FontSize',13,...
                          'Position',[250 390 90 30],...
                          'Callback',@Sentence_value);
                      
                 uicontrol('Style','text',...
                           'Position',[360 410 150 30],...
                           'String','Words',...
                           'FontName','Trebuchet',...
                           'FontSize',13);

	hWords = uicontrol('Style','edit',...
                       'FontName','Trebuchet',...
                       'FontSize',13,...
                       'Position',[360 390 150 30],...
                       'Callback',@Words_value);
                   
                   uicontrol('Style','text',...
                             'Position',[535 410 160 30],...
                             'String','Phonems',...
                             'FontName','Trebuchet',...
                             'FontSize',13);

	hPhonems = uicontrol('Style','edit',...
                         'FontName','Trebuchet',...
                         'FontSize',13,...
						 'Position',[535 390 160 30],...
                         'Callback',@Phonems_value);
                    
    hSearch = uicontrol('Style','pushbutton',...
                        'FontName','Trebuchet',...
                        'Enable','off',...
                        'FontSize',13,...
                        'FontWeight','bold',...
                        'Position',[605 320 100 30],...
                        'String','Search',...
                        'Callback',{@Search_value,1});

	hResults = uicontrol('Style','listbox',...
                         'FontName','Trebuchet',...
                         'FontSize',13,...
                         'Position',[50 45 350 300],...
						 'String','Results',...
                         'Callback',@Results_Value);
    
    hInfo = uicontrol('Style','pushbutton',...
                      'FontName','Trebuchet',...
                      'Enable','off',...
                      'FontSize',13,...
                      'FontWeight','bold',...
                      'Position',[450 320 100 30],...
                      'String','Info',...
                      'Callback',{@Info_Value,1});
                  
    hInfoText = uicontrol('Style','text',...
                          'FontName','Trebuchet',...
                          'Visible','off',...
                          'FontSize',12,...
                          'Position',[430 100 100 200],...
                          'String','InfoText');
                  
    hPlay = uicontrol('Style','pushbutton',...
                      'FontName','Trebuchet',...
                      'Enable','off',...
                      'FontSize',13,...
                      'FontWeight','bold',...
                      'Position',[450 50 100 30],...
                      'String','Play',...
                      'BackgroundColor',[0 0.73 0],...
                      'Callback',{@Play_Value,1});
                  
    hStop = uicontrol('Style','pushbutton',...
                      'FontName','Trebuchet',...
                      'Enable','off',...
                      'FontSize',13,...
                      'FontWeight','bold',...
                      'Position',[600 50 100 30],...
                      'String','Stop',...
                      'BackgroundColor',[0.73 0 0],...
                      'Callback',{@Stop_Value,1});

    handles = struct ('hFigure',hFigure,...
                      'hDirectory',hDirectory,...
                      'hDirInfo',hDirInfo,...
                      'hGender',hGender,...
                      'hPerson',hPerson,...
                      'hSentence',hSentence,...
                      'hWords',hWords,...
                      'hPhonems',hPhonems,...
                      'hSearch',hSearch,...
                      'hResults',hResults,...
                      'hInfo',hInfo,...
                      'hInfoText',hInfoText,...
                      'hPlay',hPlay,...
                      'hStop',hStop);
                  
        
        if ~isempty(obj.Database)
            hDirInfo.String = 'Database successfully loaded';
        end
        
        if strcmp(obj.GUI.hDirInfo.String,'Database successfully loaded')
            hSearch.Enable = 'on';
        end
    
end
