function handles = DatabaseGUI (obj)
% OPENGUI


    % Create and then hide the UI as it is being constructed.
    hfg = figure('Visible','on',...
                 'MenuBar','none',...
                 'Resize','off',...
                 'NumberTitle','off',...
                 'Name','Search Audio Data',...
                 'Position',[400 400 786 512]);
	
    % Centering the Gui
    movegui(hfg,'center');
    
    % Construct the components.
    hDirectory = uicontrol('Style','edit',...
						'Position',[50 450 250 30],...
        				'String','Edit Direction',...
                        'FontName','Trebuchet',...
                        'FontSize',13,...
						'Callback',@searchDatabase);
                    
    hDirInfo = uicontrol('Style','text',...
                         'Position',[350 445 350 30],...
                         'String','Ausgabetext',...
                         'FontName','Trebuchet',...
                         'Enable','off',...
                         'FontSize',13);
                     
    hTextGender = uicontrol('Style','text',...
                            'Position',[45 405 80 30],...
                            'String','Gender',...
                            'FontName','Trebuchet',...
                            'FontSize',13);

    hGender = uicontrol('Style','popupmenu',...
						'Position',[45 385 80 30],...
                        'FontName','Trebuchet',...
                        'FontSize',13,...
						'String',{'','Male','Female'});
                    
    hTextPerson = uicontrol('Style','text',...
                            'Position',[125 405 80 30],...
                            'String','Person',...
                            'FontName','Trebuchet',...
                            'FontSize',13);

	hPerson = uicontrol('Style','popupmenu',...
						'Position',[125 385 80 30],...
                        'FontName','Trebuchet',...
                        'FontSize',13,...
						'String',{'','cpm0','vmh0','arc0','aem0','adc0','alk0',...
                                    'aeb0','alr0','bgt0','tlg0','bma1','apb0',...
                                    'add0','blv0','bcg0','bcg1'});
                                
    hTextSentencID = uicontrol('Style','text',...
                               'Position',[215 410 80 30],...
                               'String','SentenceID',...
                               'FontName','Trebuchet',...
                               'FontSize',13);

	hSentence = uicontrol('Style','edit',...
                          'FontName','Trebuchet',...
                          'FontSize',13,...
                          'Position',[215 390 80 30]);
                      
    hTextWords = uicontrol('Style','text',...
                           'Position',[310 410 150 30],...
                           'String','Words',...
                           'FontName','Trebuchet',...
                           'FontSize',13);

	hWords = uicontrol('Style','edit',...
                       'FontName','Trebuchet',...
                       'FontSize',13,...
                       'Position',[310 390 150 30]);
                   
    hTextPhonems = uicontrol('Style','text',...
                             'Position',[475 410 150 30],...
                             'String','Phonems',...
                             'FontName','Trebuchet',...
                             'FontSize',13);

	hPhonems = uicontrol('Style','edit',...
                         'FontName','Trebuchet',...
                         'FontSize',13,...
						 'Position',[475 390 150 30]);
                    
    hSearch = uicontrol('Style','pushbutton',...
                        'FontName','Trebuchet',...
                        'Enable','off',...
                        'FontSize',13,...
                        'FontWeight','bold',...
                        'Position',[650 390 100 30],...
                        'String','Search');

	hResults = uicontrol('Style','listbox',...
                         'FontName','Trebuchet',...
                         'FontSize',13,...
                         'Position',[50 45 350 300],...
						 'String','Results');
    
    hInfo = uicontrol('Style','pushbutton',...
                      'FontName','Trebuchet',...
                      'Enable','off',...
                      'FontSize',13,...
                      'FontWeight','bold',...
                      'Position',[450 320 100 30],...
                      'String','Info');
                  
    hInfoText = uicontrol('Style','text',...
                          'FontName','Trebuchet',...
                          'Visible','off',...
                          'FontSize',12,...
                          'Position',[430 100 100 200],...
                          'String','InfoText');
                  
    hPlay = uicontrol('Style','pushbutton',...
                      'FontName','Trebuchet',...
                      'Enable','off',...
                      'FontSize',13,...
                      'FontWeight','bold',...
                      'Position',[450 50 100 30],...
                      'String','Play',...
                      'BackgroundColor',[0 0.73 0]);
                  
    hStop = uicontrol('Style','pushbutton',...
                      'FontName','Trebuchet',...
                      'Enable','off',...
                      'FontSize',13,...
                      'FontWeight','bold',...
                      'Position',[600 50 100 30],...
                      'String','Stop',...
                      'BackgroundColor',[0.73 0 0]);

    handles = struct ('hDirection',hDirection,...
                      'hDirInfo',hDirInfo,...
                      'hGender',hGender,...
                      'hPerson',hPerson,...
                      'hSentence',hSentence,...
                      'hWords',hWords,...
                      'hPhonems',hPhonems,...
                      'hSearch',hSearch,...
                      'hResults',hResults,...
                      'hInfo',hInfo,...
                      'hInfoText',hInfoText,...
                      'hPlay',hPlay,...
                      'hStop',hStop);

end
